plugins:
  assign_enabled:
    default: false
    client: true
  assigns_by_staff_mention: false
  unassign_creates_tracking_post: true
  assigns_public: false
  assign_self_regex: ""
  assign_other_regex: ""
  unassign_on_close: false
  unassign_on_group_archive: false
  assigns_user_url_path:
    client: true
    default: "/latest?assigned={username}"
  assign_mailer_enabled: false
  remind_assigns_frequency:
    client: true
    enum: "RemindAssignsFrequencySiteSettings"
    default: 0
  max_assigned_topics:
    client: true
    default: 10
    min: 1
  assign_allowed_on_groups:
    client: true
    type: group_list
    list_type: compact
    default: ''
    allow_any: false
    refresh: true
